### ISSUE TITLE
Is scala 2.10.5 supported?

### ISSUE THREAD

**Issue by atikinn** [circe/circe-config#11]
```
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.circe:circe-config_2.10:0.4.0 (/Users/ivan/Development/project_test/build.sbt#L720)
```

**Comment by jonas** [comment]
Not at the moment. A quick initial test suggest that the tests will require some changes to make all the required implicits available. Regardless I will try to publish for that Scala version when I find some time.

**Comment by jonas** [comment]
I had problems publishing using sbt to ended up manually uploading the artifacts for Scala 2.10.

They are now available in Maven Central: https://repo1.maven.org/maven2/io/circe/circe-config_2.10/0.4.0/
