### ISSUE TITLE
Publish with dependency on circe 0.14.x

### ISSUE THREAD

**Issue by kamilkloch** [circe/circe-config#336]
Hello, `circe-config` has become incompatible with `http4s` 0.23.16. Any chance of cutting the release based on `circe` 0.14.3? Thank you!

**Comment by ant8e** [comment]
+1

**Comment by mamos-helloself** [comment]
So it looks like this change has been merged into master, but no new release has been made. Can any of the maintainers do a new release? I built my own version from a clone of the source on master and it seems to work. Any reason not to?

**Comment by zarthross** [comment]
Can you provide more details on the error you are seeing?

**Comment by mamos-helloself** [comment]
Thank you. I was about to have to support an internal fork

**Comment by fthomas** [comment]
circe-config 0.9.0 with the dependency on circe 0.14.3 is now released.
