### ISSUE TITLE
Release using circe-core 0.14.6

### ISSUE THREAD

**Issue by awilliamsOM1** [circe/circe-config#403]
The latest version of circe-config requires circe-core 0.14.3 version. The latest version of circe-core is 0.14.6.

There has already been a commit with the upgraded dependency into the master branch https://github.com/circe/circe-config/commit/b5ebb38a197cf02896788a56aabc013b4dbf52bc .

It would be nice to do a new release of circe-config to include the latest version of circe-core to allow people to upgrade who are using strict builds.

**Comment by fthomas** [comment]
Just published [0.10.1](https://github.com/circe/circe-config/releases/tag/v0.10.1).
