### ISSUE TITLE
Convert Config back into Properties object

### ISSUE THREAD

**Issue by yuer2016** [circe/circe-config#80]
Some APIs such as Apache Kafka require their configuration to be done with Properties objects. It would be nice if typesafe Config's could be converted back into Properties, e.g. to do some fallback logic, and then plug into their systems.

**Comment by jonas** [comment]
Lightbend Config doesn't provide a way to convert a Config or ConfigObject to Properties so I am not sure this functionality belongs in this library. For example, how should lists be represented.

**Comment by yuer2016** [comment]
ow I have adopted a compromise solution.
`
sinks = {
        produces = {
          bootstrap.servers = "192.0.0.1:9092",
          max.block.ms = "500",
          #compression.type = "",
          request.timeout.ms = "6000",
          batch.size = "1024",
          #send.buffer.bytes = "",
          retries = "409600",
          acks = "1",
          retry.backoff.ms = "256",
          metadata.max.age.ms = "30000",
          key.serializer = "org.apache.kafka.common.serialization.StringSerializer",
          value.serializer = "org.apache.kafka.common.serialization.ByteArraySerializer",
          max.request.size = "4096",
          linger.ms = "0",
          metrics.sample.window.ms = "30000",
          max.in.flight.requests.per.connection = "5"
        }
      }

 def loadKafkaProducesSetting(): Map[String, Object] = {
    val config = configLoader.as[KafkaProducesSetting]("selene.bridge.kafka.sinks").right.get
    propsFromConfig(config.produces)
  }
private[this] def propsFromConfig(config: Config): Map[String, Object] = {
    import scala.collection.JavaConverters._
    val map: Map[String, Object] = config.entrySet()
      .asScala
      .map(entry =>
        entry.getKey -> entry.getValue.unwrapped())(collection.breakOut)
    map
  }
`

**Comment by yuer2016** [comment]
Now I have adopted a compromise solution.

```
sinks = {
produces = {
bootstrap.servers = "192.0.0.1:9092",
max.block.ms = "500",
#compression.type = "",
request.timeout.ms = "6000",
batch.size = "1024",
#send.buffer.bytes = "",
retries = "409600",
acks = "1",
retry.backoff.ms = "256",
metadata.max.age.ms = "30000",
key.serializer = "org.apache.kafka.common.serialization.StringSerializer",
value.serializer = "org.apache.kafka.common.serialization.ByteArraySerializer",
max.request.size = "4096",
linger.ms = "0",
metrics.sample.window.ms = "30000",
max.in.flight.requests.per.connection = "5"
}
}

def loadKafkaProducesSetting(): Map[String, Object] = {
val config = configLoader.as[KafkaProducesSetting].right.get
propsFromConfig(config.produces)
}
private[this] def propsFromConfig(config: Config): Map[String, Object] = {
import scala.collection.JavaConverters._
val map: Map[String, Object] = config.entrySet()
.asScala
.map(entry =>
entry.getKey -> entry.getValue.unwrapped())(collection.breakOut)
map
}

```

**Comment by fthomas** [comment]
Closing since this is out of scope for circe-config.
